run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - scopelint
    - interfacer
    - golint
    - maligned
    - gochecknoglobals
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - staticcheck
      - goerr113
      - funlen
      - paralleltest
      - tparallel
      - exhaustivestruct
