// Code generated by MockGen. DO NOT EDIT.
// Source: reposiroty.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	domain "github.com/g-chicken/mah-jong/app/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockPlayerRepository is a mock of PlayerRepository interface.
type MockPlayerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerRepositoryMockRecorder
}

// MockPlayerRepositoryMockRecorder is the mock recorder for MockPlayerRepository.
type MockPlayerRepositoryMockRecorder struct {
	mock *MockPlayerRepository
}

// NewMockPlayerRepository creates a new mock instance.
func NewMockPlayerRepository(ctrl *gomock.Controller) *MockPlayerRepository {
	mock := &MockPlayerRepository{ctrl: ctrl}
	mock.recorder = &MockPlayerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerRepository) EXPECT() *MockPlayerRepositoryMockRecorder {
	return m.recorder
}

// CreatePlayer mocks base method.
func (m *MockPlayerRepository) CreatePlayer(c context.Context, name string) (*domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlayer", c, name)
	ret0, _ := ret[0].(*domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlayer indicates an expected call of CreatePlayer.
func (mr *MockPlayerRepositoryMockRecorder) CreatePlayer(c, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlayer", reflect.TypeOf((*MockPlayerRepository)(nil).CreatePlayer), c, name)
}

// GetPlayerByName mocks base method.
func (m *MockPlayerRepository) GetPlayerByName(c context.Context, name string) (*domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerByName", c, name)
	ret0, _ := ret[0].(*domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerByName indicates an expected call of GetPlayerByName.
func (mr *MockPlayerRepositoryMockRecorder) GetPlayerByName(c, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerByName", reflect.TypeOf((*MockPlayerRepository)(nil).GetPlayerByName), c, name)
}

// GetPlayers mocks base method.
func (m *MockPlayerRepository) GetPlayers(c context.Context) ([]*domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayers", c)
	ret0, _ := ret[0].([]*domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayers indicates an expected call of GetPlayers.
func (mr *MockPlayerRepositoryMockRecorder) GetPlayers(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayers", reflect.TypeOf((*MockPlayerRepository)(nil).GetPlayers), c)
}

// MockRDBGetterRepository is a mock of RDBGetterRepository interface.
type MockRDBGetterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRDBGetterRepositoryMockRecorder
}

// MockRDBGetterRepositoryMockRecorder is the mock recorder for MockRDBGetterRepository.
type MockRDBGetterRepositoryMockRecorder struct {
	mock *MockRDBGetterRepository
}

// NewMockRDBGetterRepository creates a new mock instance.
func NewMockRDBGetterRepository(ctrl *gomock.Controller) *MockRDBGetterRepository {
	mock := &MockRDBGetterRepository{ctrl: ctrl}
	mock.recorder = &MockRDBGetterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRDBGetterRepository) EXPECT() *MockRDBGetterRepositoryMockRecorder {
	return m.recorder
}

// GetRDBOperator mocks base method.
func (m *MockRDBGetterRepository) GetRDBOperator(c context.Context) domain.RDBOperator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRDBOperator", c)
	ret0, _ := ret[0].(domain.RDBOperator)
	return ret0
}

// GetRDBOperator indicates an expected call of GetRDBOperator.
func (mr *MockRDBGetterRepositoryMockRecorder) GetRDBOperator(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRDBOperator", reflect.TypeOf((*MockRDBGetterRepository)(nil).GetRDBOperator), c)
}

// MockRDBOperator is a mock of RDBOperator interface.
type MockRDBOperator struct {
	ctrl     *gomock.Controller
	recorder *MockRDBOperatorMockRecorder
}

// MockRDBOperatorMockRecorder is the mock recorder for MockRDBOperator.
type MockRDBOperatorMockRecorder struct {
	mock *MockRDBOperator
}

// NewMockRDBOperator creates a new mock instance.
func NewMockRDBOperator(ctrl *gomock.Controller) *MockRDBOperator {
	mock := &MockRDBOperator{ctrl: ctrl}
	mock.recorder = &MockRDBOperatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRDBOperator) EXPECT() *MockRDBOperatorMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockRDBOperator) Exec(c context.Context, query string, args ...interface{}) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{c, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockRDBOperatorMockRecorder) Exec(c, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{c, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockRDBOperator)(nil).Exec), varargs...)
}

// Get mocks base method.
func (m *MockRDBOperator) Get(c context.Context, query string, args []interface{}, dist ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{c, query, args}
	for _, a := range dist {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRDBOperatorMockRecorder) Get(c, query, args interface{}, dist ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{c, query, args}, dist...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRDBOperator)(nil).Get), varargs...)
}

// Select mocks base method.
func (m *MockRDBOperator) Select(c context.Context, query string, args []interface{}, scanFunc func(*sql.Rows) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", c, query, args, scanFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Select indicates an expected call of Select.
func (mr *MockRDBOperatorMockRecorder) Select(c, query, args, scanFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRDBOperator)(nil).Select), c, query, args, scanFunc)
}

// MockConfigRepository is a mock of ConfigRepository interface.
type MockConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepositoryMockRecorder
}

// MockConfigRepositoryMockRecorder is the mock recorder for MockConfigRepository.
type MockConfigRepositoryMockRecorder struct {
	mock *MockConfigRepository
}

// NewMockConfigRepository creates a new mock instance.
func NewMockConfigRepository(ctrl *gomock.Controller) *MockConfigRepository {
	mock := &MockConfigRepository{ctrl: ctrl}
	mock.recorder = &MockConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRepository) EXPECT() *MockConfigRepositoryMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockConfigRepository) GetConfig(c context.Context) (*domain.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", c)
	ret0, _ := ret[0].(*domain.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockConfigRepositoryMockRecorder) GetConfig(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockConfigRepository)(nil).GetConfig), c)
}
